## 3. Stock

Immer wieder schön, dich wieder zu sehen.  
Wird immer schlimmer, wenn du gehst.  
Am Bahnhof stehst, um den Zug zu nehmen.  
Sich lang' nicht wiedersehen.  
Wird schon irgendwie gehen,  
Macht manchmal traurig.  
  
Ich würd' gerne mit dir in 'ner Altbauwohnung wohnen.  
Zwei Zimmer, Küche, Bad und 'nen kleinen Balkon.  
Ich würd' gern mit dir in 'ner Altbauwohnung wohnen.  
Mit 'nem kleinen Balkon.  
  
  
  
  
Immer wieder Warten.  
In leisen Telefonaten.  
Worauf genau, weiß ich nicht, vielleicht auf dein Gesicht.  
Erzähl mir von dir, um mich abzulenken,  
Wenn das traurige Gedanken denken beginnt.  
Beide blind, jeder auf seine Weise Schisser.  
Vertrauen ist gut, Kontrolle für Besserwisser.  
  
Ich würd' gerne mit dir in 'ner Altbauwohnung wohnen.  
Zwei Zimmer, Küche, Bad und 'nen kleiner Balkon.  
Ich würd' gern mit dir in 'ner Altbauwohnung wohnen.  
Mit 'nem kleinen Balkon.  
  
Unsere Telefonate haben kein  
Ende aus und gut gab es  
Nie legst du als Erste  
Auf meinem Hochbett liegt ein Bild von dir.  
  
Unsere Telefonate haben kein  
Ende aus und gut gab es  
Nie legst du als Erste  
Auf meinem Hochbett liegt ein Bild von dir.  
  
Ich würd' gerne mit dir in 'ner Altbauwohnung wohnen.  
Zwei Zimmer, Küche, Bad und 'nen kleinen Balkon.  
Ich würd' gern mit dir in 'ner Altbauwohnung wohnen.  
Ich würde auch manchmal morgens Brötchen holen.
