## Das Krokodil

Brauchen Sie das Zimmer bis um zehn?  
Frühstück gibt's ab acht  
Kaffee, Marmelade und verdünnten Orangensaft  
Eigentlich ist jeder Abend eine lange Nacht  
Auto fahren, sitzen, schlafen mit dem Kopf am Fenster  
Und hinten liegen die Jacken oder einer von uns pennt da  
Und manchmal fahren wir raus und machen Pause  
Und morgen ist München und irgendwann ist auch wieder zu Hause  
Die Zigaretten werden vorgedreht vor jedem Raststättenhalt  
Das Krokodil raucht zu viel (Ach ja?)  
Das Krokodil raucht zu viel (Ach ja?)  
Das Krokodil, das Krokodil  
Das Krokodil raucht zu viel  
Schön, dass ihr da seid, wurde auch Zeit  
Und wo wart ihr gestern und wie lange seid ihr schon auf Tour?  
Und Essen gibt's um 18 Uhr  
Toilette ist auf dem Gang  
Dahinten sind die Garderoben  
Dritte Tür links und dann ganz nach oben  
Und Duschen haben wir leider nicht  
Sorry für das Neonröhrenlicht  
Und wenn ihr Fragen habt, fragt mich  
Und wenn ihr mich fragt  
Ich glaub, ihr kommt bestimmt mal ganz groß raus  
Und bevor ich es vergesse  
Im ganzen Haus herrscht Rauchverbot  
Das Krokodil raucht zu viel (Ach ja?)  
Das Krokodil raucht zu viel (Ach ja?)  
Das Krokodil, das Krokodil  
Das Krokodil raucht zu viel  
Was soll das denn heißen?  
Im ganzen Haus ist Rauchverbot?  
Das Krokodil raucht zu viel (Ach ja?)  
Das Krokodil raucht zu viel (Ach ja?)  
Das Krokodil, das Krokodil  
Das Krokodil raucht zu viel
