## Marie

Die Vögel scheißen vom Himmel  
Und ich schau' dabei zu  
Und ich bin hier und alleine  
Marie, wo bist du?  
Marie, wo bist du?  
  
Manchmal denk' ich die Welt ist 'n Abgrund  
Und wir fallen, aber nicht allen fällt das auf  
Und so nimmt alles, alles seinen Lauf  
Mein bester Freund ist viel zu jung gestorben  
Und schon so lange hab' ich keine Mutter mehr  
Meistens fehlen mir dafür die Worte  
Und wenn sie kommen, dann weiß ich nicht woher  
Und wärst du hier wüsste ich für wen  
  
Die Vögel scheißen vom Himmel  
Und ich schau' dabei zu  
Und ich bin hier und alleine  
Marie, wo bist du?  
Marie, wo bist du?  
  
  
  
  
Ich glaub' mein Blick ist vom Vorüberzieh'n der Städte  
So müde, dass er nichts mehr hält  
Mir ist als ob es tausend Städte gäbe  
Und hinter tausend Städten keine Welt  
Aber die ist ja eh 'n Abgrund  
Und wir fallen, ich glaub' mir gefällt's  
Und ich weiß jetzt, alles dreht sich  
Alles dreht sich, wenn du dich verliebst  
  
Die Vögel scheißen vom Himmel  
Und ich schau' dabei zu  
Und ich bin hier und alleine  
Marie, wo bist du?  
Marie, wo bist du?  
  
Marie, Marie, Marie, Marie  
Marie, Marie, Marie, Marie  
Marie, Marie, Marie, Marie  
Marie, Marie, Marie, Marie  
  
Die Vögel scheißen vom Himmel  
Und ich schau' dabei zu  
  
Marie, Marie, Marie, Marie  
Marie, Marie, Marie, Marie  
Marie, Marie, Marie, Marie  
Marie, Marie, Marie, Marie  
  
Marie, wo bist du?  
Wo bist du, Marie?
