## Nur wegen dir

Ich schlafe und träume  
Ich träum' in letzter Zeit so viel  
Und keiner meiner Träume  
War ein Traum, der mir gefiel  
  
Ich schlafe und träume  
Von so vielen Dingen  
Und ich hab' mich nie getraut  
Über meine Träume zu singen  
  
Und ich wach' auf und ich bin wieder so glücklich  
Und alles nur wegen dir  
Und ich wach' auf und ich bin wieder so glücklich  
Und alles nur wegen dir  
Nur wegen dir  
  
  
  
  
Ich träume, ich laufe  
Ich träum', ich lauf' so schnell ich kann  
Und dann ist da eine Straße ohne Licht  
Und dann fängt es zu regnen an  
Und neben mir mein Bruder  
Und er trägt ein FC-Tricot  
Und er sagt zu mir am Ende  
Sind wir allein und ziemlich tot  
Und ich sag'  
  
Wenn man das so sieht, dann ist das wirklich so  
Wenn man das so sieht, dann ist das wirklich so  
Wenn man das so sieht, dann ist das-  
  
Und ich wach' auf und ich bin wieder so glücklich  
Und alles nur wegen dir  
Und ich wach' auf und ich bin wieder so glücklich  
Und alles nur wegen dir  
Nur wegen dir  
  
Und alles nur wegen dir  
Und alles nur wegen dir  
Und alles nur wegen dir  
Und alles nur wegen dir  
Und alles nur wegen dir  
Und alles nur wegen dir  
Und alles nur wegen dir  
Nur wegen dir
