## Ich geh heut nicht mehr tanzen

Ich weiß, ich hab' gesagt  
Ich bin heute am Start  
Aber ich komm' nicht klar und da  
Wo ich schon tausendmal war  
Will ich heute nicht hin  
Weil da immer die gleichen Leute sind  
Und weil ich müde bin  
Müde, müde, müde bin  
Und weil ich müde bin  
Weil ich müde, müde, müde bin  
  
Ich glaub', ich geh' heut' nicht mehr tanzen  
Ich glaub', ich geh' heut' nicht mehr raus  
Ich glaub', ich rauche heute Pflanzen  
Und bleib' allein zu Haus  
  
Ich glaub', ich geh' heut' nicht mehr tanzen  
Ich glaub', ich geh' heut' nicht mehr raus  
Ich glaub', ich rauche heute Pflanzen  
Und bleib' allein zu Haus  
  
  
  
  
Ich bin noch immer so müde von gestern  
Und suche bei Netflix nach einem Western  
Die Jungs mit Revolvern helfen vergessen  
Dass man trinkt um zu vergessen  
Mein Magen sagt, ich müsste was essen  
Ernähr' mich seit Wochen nur noch von Resten  
  
Vietnamesisch neben dem Bett  
Ich hab' nie was im Kühlschrank  
Ich warte noch immer darauf, dass ich wieder fühlen kann  
Ich bin noch immer so müde von gestern  
Ich warte noch immer darauf, dass ich wieder fühlen kann  
Ich suche bei Netflix nach einem Western  
  
Ich glaub', ich geh' heut' nicht mehr tanzen  
Ich glaub', ich geh' heut' nicht mehr raus  
Ich glaub', ich rauche heute Pflanzen  
Und bleib' allein zu Haus  
  
Ich glaub', ich geh' heut' nicht mehr tanzen  
Ich glaub', ich geh' heut' nicht mehr raus  
Ich glaub', ich rauche heute Pflanzen  
Und bleib' allein zu Haus  
Ich geh' heut' nicht mehr tanzen  
  
Vietnamesisch neben dem Bett  
Ich hab' nie was im Kühlschrank  
Vietnamesisch neben dem Bett  
Ich hab' nie was im Kühlschrank  
Ernähr' mich seit Wochen nur noch von Resten  
Vietnamesisch  
Ernähr' mich seit Wochen nur noch von Resten  
  
Ich glaub', ich geh' heut' nicht mehr tanzen  
Ich glaub', ich geh' heut' nicht mehr raus  
Ich glaub', ich rauche heute Pflanzen  
Und bleib' allein zu Haus
