## Freitagabend

Freitagabend, Freitagabend, Freitagabend  
Freitag  
  
In der Innenstadt fahr'n junge Männer  
Autos, die ihn' nicht gehören  
Sie werden heute Nacht so oft auf die Familie schwören  
Irgendwo im Gewerbegebiet, da wo sich alle berauschen  
Fragen meine Freunde Fremde  
"Kannst du mir was verkaufen?"  
  
Freitagabend, Freitagabend  
Freitagabend, Freitagabend  
  
  
  
  
Paare in meinem Alter gehen kuscheln im Kino  
Und dann machen sie Fotos und trinken weißen Vino  
Familien bestellen japanisch, Lieferdienste brauchen zu lang  
Junge Frauen schminken sich und dann fängt Freitagabend an  
  
Freitagabend, Freitagabend  
Freitagabend, Freitagabend  
  
In der Innenstadt fahren junge Männer  
Autos gegen eine Wand  
Junge Leute kauen Kiefer  
Und verlieren den Verstand  
  
Freitagabend, Freitagabend  
Freitagabend, Freitagabend  
  
Wenn du heut' Abend noch was machst, sag mir Bescheid  
Wenn du heut' Abend noch was machst, sag mir Bescheid  
Wenn du heut' Abend noch was machst, sag mir Bescheid
