## Weiße Wand

Ich bin allein mit der weißen Wand  
Und meinem scheiß Verstand.  
Ich weiß nicht, man  
Ich bin allein mit der weißen Wand  
Und meinem scheiß Verstand  
Ich weiß nicht, man  
  
Ich war schwarz in 'nem weißen Land  
Obwohl ich mir die Reise leisten kann  
Und ich schau' mir die Schlagzeilen an  
Und irgendwas hat sich eingebrannt  
Flüchtlingskrise fühlt sich an wie Reichstagsbrand  
Auch wenn ich das nicht vergleichen kann  
  
Weißt du, man  
Ich bin jung und weiß in 'nem reichen Land  
Mein Kreissaal war umkreist von 'ner weißen Wand  
Ich bin jung und weiß in 'nem reichen Land  
Mein Kreissaal war umkreist von 'ner weißen Wand  
Scheiße, man  
  
  
  
  
Ich bin keiner von denen, die weiterwissen  
Ehrlich gesagt, ich krieg' selber nie was geschissen  
Und ich weiß nicht, wann man die Decke aus Glas einreißen kann  
Die Decke aus Glas ist 'ne weiße Wand  
Auch wenn ich das nicht beweisen kann  
  
Ich fahr' schwarz in 'nem weißen Land  
Das man nicht mit jedem Pass bereisen kann  
Ich fahr' schwarz in 'nem weißen Land  
Das man nicht mit jedem Pass bereisen kann  
  
Ich bin allein mit der weißen Wand  
Und meinem scheiß Verstand  
Ich weiß nicht, man  
Und jeder weiß, dass sie weiß ist  
Und jeder weiß, dass sie weiß ist  
Ich bin allein mit der weißen Wand  
Und meinem scheiß Verstand  
Ich weiß nicht, man  
Und jeder weiß, dass sie weiß ist  
Und jeder weiß, dass sie weiß ist  
Jeder weiß es
