## Hinter klugen Sätzen

Ich versteck' mich  
Hinter klugen Sätzen  
Ziehe Konsequenzen  
Die gar keine sind  
  
Ich versetze Freunde  
Die mich schätzen  
Die an mich denken  
Auch wenn ich nicht erreichbar bin  
  
Ich bin nicht gut darin  
Dinge zu beenden  
Und ich will Zeit verschwenden  
Und weiß noch nicht womit  
  
Und ich habe  
Fernweh ohne Ende  
Fernweh für das Fremde  
Weil ich mir selber fremd geworden bin  
  
  
  
  
Ich versteck' mich  
Hinter klugen Sätzen  
Konsequenzen  
Die gar keine sind  
  
Ich versteck' mich  
Hinter klugen Sätzen  
Ziehe Konsequenzen  
Die gar keine sind  
  
Und ich merk' nicht  
Dass ich gerne wette  
Und immer alles setze  
Weil ich verlieren will  
  
Und ich weiß  
Dass ich ruhiger werden müsste  
Wenn ich nur wüsste  
Wie man schweigen lernen kann  
  
Und ich bin leider  
Selten an der Küste  
Die ich so sehr vermisse  
Weil alles anders ist am Strand  
  
Und ich habe  
Fernweh ohne Ende  
Fernweh für das Fremde  
Weil ich mir selber fremd geworden bin  
  
Ich versteck' mich  
Hinter klugen Sätzen  
Konsequenzen  
Die gar keine sind  
  
Ich versteck' mich  
Hinter klugen Sätzen  
Ziehe Konsequenzen  
Die gar keine sind  
  
Ich belüge  
Mich auf meine Weise  
Eher laut als leise  
Damit sich irgendwas in mir bewegt  
  
Ich habe Angst zu lieben  
Immer nur am Zweifeln  
Im Hinterkopf das Scheitern  
Weil alles irgendwann vergeht  
Weil alles irgendwann vergeht
