## Sieben Jahre

Du fragst dich immer noch  
Du fragst dich immer noch  
Was wäre wenn, was wäre wenn  
Und du weißt auch  
Und du weißt auch  
Dass keiner eine Antwort kennt  
Du sagst  
  
Manchmal wachst du morgens auf  
Und weißt nich mehr was wahr ist  
Was wahr ist  
Und dann denkst du für ein paar Sekunden  
Dass sie noch da ist  
Noch da ist  
  
Vor sieben Jahren  
Vor sieben Jahren  
Hast du sie das letzte Mal gesehen  
Aber was war, ist  
Aber was war, ist  
Für dich noch immer wunderschön  
  
  
  
  
Du sagst  
Manchmal wachst du morgens auf  
Und weißt nich mehr was wahr ist  
Was wahr ist  
Und dann denkst du für ein paar Sekunden  
Dass sie noch da ist  
Noch da ist  
  
Wenn du deswegen  
Nich mehr weiterweißt  
Willst du wieder auf das große Meer hinaus  
Weil du merkst, dass es  
Für dich weitergeht  
So was kriegst du aus'm Herzen nicht mehr raus  
So was kriegst du aus'm Herzen nicht mehr raus  
  
Und du erzählst noch immer  
So viel von ihr  
Dabei ist sie sieben Jahre nicht mehr hier  
Und du erzählst noch immer  
So viel von ihr  
Dabei ist sie sieben Jahre nicht mehr hier  
  
Wenn du deswegen  
Nicht mehr weiterweißt  
Willst du wieder aus das große Meer hinaus  
Weil du merkst, dass es  
Für dich weitergeht  
So was kriegst du aus'm Herzen nicht mehr raus  
So was kriegst du aus'm Herzen nicht mehr raus  
So was kriegst du aus'm Herzen nicht mehr raus
