## Jenny Jenny

Der Tag beginnt im Spiegel  
Müde Augen werden wach geschminkt  
Die Lippen rot wie Ziegel  
Und dann der Kaffee, den sie jeden Morgen trinkt  
  
Und sie trägt blau und gelb  
Sie sagt, sie wär' so gern fest angestellt  
Sie sagt, die Welt ist kleiner  
Wenn du jeden Tag fliegst  
  
Jenny Jenny, Wolkenreiter  
Lächelt einfach immer weiter  
So wie alle Flugbegleiter  
Jenny, Wolkenreiter  
Jenny Jenny, Wolkenreiter  
Lächelt einfach immer weiter  
So wie alle Flugbegleiter  
Jenny Jenny, Wolkenreiter  
  
  
  
  
Und nach jeder Landung  
Ist sie das Lächeln in der Brandung  
Zwischen tausend Passagieren, die nicht warten wollen  
Auf die Passkontrollen und den Zoll  
Und dann drei Stunden Aufenthalt  
Und Jenny trinkt den Kaffee kalt  
Und sie googelt Panama  
Vor zwei Jahr'n war sie mal zehn Minuten da  
Oh, Panama  
  
Oh, Panama (Panama)  
Oh oh oh, Panama (Panama)  
Oh oh oh, Panama (Panama)  
Oh, wie schön ist Panama (Panama)  
  
Jenny Jenny, Wolkenreiter  
Lächelt einfach immer weiter  
So wie alle Flugbegleiter  
Jenny, Wolkenreiter  
Jenny Jenny, Wolkenreiter  
Lächelt einfach immer weiter  
So wie alle Flugbegleiter  
Jenny Jenny, Wolkenreiter  
  
Willkommen an Bord  
Willkommen an Bord  
Willkommen an Bord  
Willkommen an Bord  
  
Jeden Tag zehntausend Meilen über dem Meer  
Sie sagt, sie kommt manchmal nach Hause  
Und weiß nicht mehr woher  
  
Jenny Jenny, Wolkenreiter  
Lächelt einfach immer weiter  
So wie alle Flugbegleiter  
Jenny, Wolkenreiter  
Jenny Jenny, Wolkenreiter  
Lächelt immer weiter  
So wie alle Flugbegleiter  
Jenny, Wolkenreiter  
  
Willkommen an Bord
