## Alle Fragen

Du fährst in die Heimat  
Und alles wird leiser  
Und irgendwie kleiner  
Du fährst in die Heimat  
Du glaubst mittlerweile  
Dass hier alle den Schein wahren  
  
Das Erste, was dir auffällt  
Wenn du endlich ankommst  
Ist Vergangenheit  
Das Zweite, was dir auffällt  
Wenn du dich dann umschaust  
Ist Veränderung  
Das Dritte, was dir auffällt  
Wenn du aussteigst  
Ist, dass du alleine bist  
  
Du warst ewig nicht mehr hier  
Und das letzte Mal mit ihr  
Du warst ewig nicht mehr hier  
Und das letzte Mal mit ihr  
  
  
  
  
Du fährst in die Heimat  
Und alles wird irgendwie kleiner  
Und irgendwie leiser  
Du fährst in die Heimat  
Nach so langer Zeit und  
Auf einmal vergleichst du  
Den, der hier weggeht  
Mit dem, der du jetzt bist  
  
Egal was du machst  
Du kannst deutlich sehen  
Du willst hier nicht bleiben  
Nie wieder leben  
Egal was du machst  
Du kannst deutlich sehen  
Du willst hier nicht bleiben und  
So schnell weg, wie es geht  
  
Das Erste, was dir auffällt  
Immer wenn du ankommst  
Ist Vergangenheit  
Das Zweite, was dir auffällt  
Wenn du wieder losfährst  
Ist Veränderung  
Das Dritte, was dir auffällt  
Wenn du dich noch umschaust  
Ist, dass du alleine bist  
Das Letzte, was dir auffällt ist  
Dass du sie immer noch vermisst  
Dass du sie immer noch vermisst  
  
Du warst ewig nicht mehr hier  
Und das letzte Mal mit ihr  
Du warst ewig nicht mehr hier  
Und das letzte Mal mit ihr  
Und alle fragen dich nach ihr  
Alle fragen  
Alle fragen  
Und alle fragen dich nach ihr  
Alle fragen  
Alle fragen  
Und alle fragen dich nach ihr  
Alle fragen  
Alle fragen  
Und alle fragen dich nach ihr  
Alle fragen  
Alle fragen  
Und alle fragen dich nach ihr
