## Du bist anders

Du bist anders  
Du hörst mir nicht zu  
Du weißt ich kann das  
Schweigen nicht so gut wie du  
  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
  
Aber ich seh' was in deinem Gesicht  
Und ich weiß nicht was es ist  
Aber ich seh' was in deinem Gesicht  
Und ich weiß nicht was es ist  
  
Dadada, dadada, dada  
Dadadadada  
  
Du bist anders  
Du hörst mir nicht zu  
Du weißt ich kann das  
Schweigen nicht so gut wie du  
  
  
  
  
Ich weiß nicht was es  
Und es macht mich wahnsinnig  
Und ich glaub' dir nicht, dass da gar nichts ist  
Ich frag' mich ob du Angst hast  
Oder ist da jemand anders?  
Fällt dir auf wie wenig du lachst?  
  
Bitte, bitte  
Sag es mir und tu nicht so als ob da gar nichts ist  
Bitte, bitte  
Sag es mir und tu nicht so als ob da gar nichts ist  
  
Aber ich seh' was in deinem Gesicht  
Und ich weiß nicht was es ist  
Aber ich seh' was in deinem Gesicht  
Und ich weiß nicht was es ist  
  
Dadada, dadada, da, dada  
Dadadadada, dada  
Dadada, dadada, da, dada  
Dadadadada, dada  
  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts  
Weil du mir nicht alles sagst  
Frag' ich dich nochmal und du sagst nichts
