## Schon krass

Weißt du, ich bin jung, und ich weiß noch nicht, warum  
Ich hab's gemacht, und nicht drüber nachgedacht  
"Ja" ist immer einfach, "nein" ist immer schwer  
Ich hab' so oft gesagt, "Ich mache das nie mehr"  
Aber ich glaub' aufm Weg nach oben  
Liegen überall Drogen  
Meine Freunde haben alle gezogen  
Ich hab' gebaut und geraucht und gelogen  
Ich hab' gebaut und geraucht  
  
Weißt du, ich weiß, wie viel's wiegt, wenn es vor mir liegt  
Und woher man's kriegt, wenn man's so sehr liebt  
Dass es keinen Tag ohne mehr gibt  
Ist schon krass, wie das alles verschiebt  
Ist schon krass, wie das alles verschiebt  
  
  
  
  
Ich weiß nicht mehr, wann  
Ich das letzte Mal nüchtern daran  
Gedacht hab' und dachte, ich kann  
Das alles vielleicht irgendwann  
Hinter mir lassen und dann  
Von vorne anfangen  
Und anders sein zu jemanden, der mich liebt  
Ist schon krass, wie das alles verschiebt  
Ist schon krass, wie das alles verschiebt  
  
Weißt du, ich weiß, wie viel's wiegt, wenn es vor mir liegt  
Und woher man's kriegt, wenn man's so sehr liebt  
Dass es keinen Tag ohne mehr gibt  
Ist schon krass, wie das alles verschiebt  
Ist schon krass, wie das alles verschiebt  
  
Weißt du, ich weiß, wie viel's wiegt, wenn es vor mir liegt  
Und woher man's kriegt, wenn man's so sehr liebt  
Dass es keinen Tag ohne mehr gibt  
Ist schon krass, wie das alles verschiebt  
Ist schon krass, wie das alles verschiebt
