## Vielleicht Vielleicht

Es ist so leicht ehrlich zu dir zu sein  
Es ist so einfach wenn ich sage nein  
Oder ich bin noch nicht so weit  
Du gibst mir Zeit  
  
Und du bist süß  
Wie du aussiehst wenn du genießt  
Dass es im Winter endlich schneit  
Du magst jede Jahreszeit  
Und morgens muss ich lächeln  
Weil mich deine Küsse wecken  
Und dann merk' ich, es ist leicht  
Weil dir so wenig reicht  
Du gibst mir Zeit  
  
Und dann denk' ich, dass es vielleicht, vielleicht  
Für immer so bleibt  
Und dann denk' ich, dass es vielleicht, vielleicht  
Für immer so bleibt  
Ja es ist leicht, leicht, leicht, leicht  
Ja es ist leicht, leicht, leicht, leicht  
  
  
  
  
Es ist so schön  
Dir zuzusehen  
Wenn du duschen gehst  
Und dann vor mir stehst  
Und sagst, es wird ein langer Tag  
Und wenn du mich dann fragst  
Was wir heut Abend machen  
Und wir zwischen Küssen lachen  
Dann merk' ich, es ist leicht  
Weil dir so wenig reicht  
Du gibst mir Zeit  
  
Und dann denk ich, dass es vielleicht, vielleicht  
Für immer so bleibt  
Und dann denk' ich, dass es vielleicht, vielleicht  
Für immer so bleibt  
Ja es ist leicht, leicht, leicht, leicht  
Ja es ist leicht, leicht, leicht, leicht  
  
Weil du siehst was ich sonst niemandem zeige  
Ich kann dir erzählen was ich mir selbst verschweige  
Und ich will, dass es für immer so bleibt  
Und ich glaube, das geht  
Vielleicht, vielleicht  
Vielleicht, vielleicht  
Vielleicht, vielleicht  
Vielleicht, vielleicht  
Und ich will, dass es für immer so bleibt  
Und ich glaube, das geht  
Vielleicht, vielleicht  
Vielleicht, vielleicht  
Vielleicht, vielleicht  
Vielleicht, vielleicht
