## Schlagschatten

Schlagschatten fallen auf mein Gesicht  
Ich sitz' im Zug und schreibe  
Ich seh' Bahnhofshallen im Sonnenlicht  
Und die, die darauf warten, zuzusteigen  
Ich glaube, ich habe schon wirklich sehr lange  
Nur aus dem Fenster geschaut  
Besonders am Abend hat jeder Gedanke  
Den ich habe, die Farbe Blau  
Die Tage zählen und untertauchen  
Sind kein Neuanfang, nur ein Ende  
Warum laufen die Tränen aus meinen Augen  
Obwohl ich an niemanden denke?  
  
  
  
  
Schlagschatten fallen, die Sonne ist rot  
Ich glaub' das kleine Glück ist groß  
Schlagschatten fallen, die Sonne ist rot  
Ich glaub' das kleine Glück ist groß  
  
Die Landschaft ist weit, zieht an mir vorbei  
Ich werde ganz langsam müde  
Vielleicht schlaf' ich ein und träum' von der Zeit  
Die mir noch bliebe  
Ich will Karten zählen und eine rauchen und  
Anfangen mein Blatt zu wenden  
Warum laufen die Tränen aus meinen Augen  
Obwohl ich an niemanden denke?  
Warum laufen die Tränen aus meinen Augen  
Obwohl ich an niemanden denke?  
  
Schlagschatten fallen, die Sonne ist rot  
Ich glaub' das kleine Glück ist groß  
Schlagschatten fallen, die Sonne scheint rot  
Ich glaub' das kleine Glück ist groß  
  
Schlagschatten fallen
