## Es geht mir gut

Du hörst dir tausend Geschichten an,  
Was ich alles machen werde, wie und wo und wann  
Und dieses und jenes  
aber alles nichts Konkretes.  
  
Ich stell mich selber dar  
als ob nichts war.  
Und ich sag:  
"Über gestern sprechen wir morgen, mach' dir keine Sorgen.  
Du machst dir unnötig Sorgen."  
  
Es geht mir gut,  
Es geht mir eigentlich immer gut.  
Es geht mir gut.  
Es geht mir gut,  
Es geht mir eigentlich immer gut.  
Es geht mir gut.  
  
  
  
  
Und dann stehst du wieder vor meiner Tür  
Und fragst mich: "Wie geht es dir?"  
Und dann sag' ich dir, was du hören willst.  
Und dann bist du wieder still.  
  
Ach weißt du, muss, muss, bei dir?  
Und sonst so? Was geht so heute Abend?  
Ach weißt du, muss, muss, bei dir? Und sonst so? Was geht heute Abend?  
Immer die gleichen Fragen.  
  
Es geht mir gut,  
Es geht mir eigentlich immer gut.  
Es geht mir gut.  
Es geht mir gut,  
Es geht mir eigentlich immer gut.  
Es geht mir gut.  
  
Und wie geht's dir denn so?  
Und das hätte ich an deiner Stelle auch gesagt.  
  
Es geht mir gut,  
Es geht mir eigentlich immer gut.  
Es geht mir gut.  
Es geht mir gut,  
Es geht mir eigentlich immer gut.  
Es geht mir gut.  
  
Frag' doch nicht so blöd!
