## What He Wanted the Most

But though he never knew  
What heartache is  
He went out for a single kiss  
  
And he told his father  
That he's never coming back  
But maybe with a broken back  
  
He was a gypsy  
From the coast  
And what he wanted the most  
Was being on his own  
All alone  
In the dark and the light every night  
And he'd want nobody to be tired  
  
  
  
  
And he'd get it  
And hide it and let me down  
He wanted it all  
In all the town  
It got to be the same for me  
And all he'd ever feel  
Is the gypsy feeling free  
  
Hey  
Hey  
Hey  
Hey  
  
That gypsy from the coast  
And what he wanted the most  
That gypsy from the coast  
And what he wanted the most  
  
All the times that he tried to lie  
He was able to set his fire  
All the people around  
Listening to his sound  
And he was crazy without no doubt  
  
And he hshfkdvsufjckxgsbdjdjck  
  
And if you like him  
Just give him some money  
Come on like him he's very funny  
  
Hey  
Hey  
Hey  
Hey  
  
That gypsy from the coast  
And what he wanted the most  
That gypsy from the coast  
And what he wanted the most  
Interval  
Oh, that gypsy from the coast  
What he wanted the most  
That gypsy from the coast  
What he wanted the most  
And though he never knew  
What heartache is  
He went out for a single kiss  
Hey
