## Neues Zimmer

In meinem neuen Zimmer steh'n noch immer die Kartons, halb ausgepackt  
und die Wand ist nackt  
Und über mir trinken lauter laute Leute Bier  
bis kurz nach vier  
und ich bin abgefuckt.  
Und die Matratze kratzte in der ersten Nacht  
ohne Lattenrost  
Ich krieg' noch keine Post  
Ummelden ist noch mehr Stress  
Gut, dass ich das eh vergess'  
  
In meinem neuen Zimmer steh'n noch immer die Kartons  
und ich weiß nicht, was ich als erstes machen soll.  
In meinem neuen Zimmer  
In meinem neuen Zimmer  
In meinem neuen Zimmer  
In meinem ... neuen Zimmer  
  
  
  
  
Jede Nacht bin ich wach,  
weil ich die neuen Geräusche um mich rum nicht richtig kenne.  
Und wenn ich endlich penne,  
ist schon wieder heller Morgen und ich  
hab' die gleichen Sorgen wie am Tag zuvor.  
Ich muss tausend Sachen machen  
und ich nehm' mir viel zu viel vor.  
Ich hab nur ausgepackt, nicht eingeräumt.  
  
Ich hab' im leeren Raum geträumt, wie es wohl aussehen könnte.  
und jetzt hilft mir die Glühbirne beim Sachen suchen,  
weil ich die festen Plätze erst noch finden muss.  
  
In meinem neuen Zimmer steh'n noch immer die Kartons  
und ich weiß nicht, was ich als erstes machen soll.  
In meinem neuen Zimmer  
In meinem neuen Zimmer  
In meinem neuen Zimmer  
In meinem neuen Zimmer
