## Länger bleiben

Die nächste Bahn kommt erst in 'ner Stunde  
komm ich hol' noch 'ne Runde  
und ich muss auch früh raus  
das ist keine gute Ausrede  
und bei dem Regen würd' ich eh nicht nach Hause geh'n  
du kannst gern mal nach draußen seh'n  
das ist 'ne viel bessere Ausrede als deine  
du weißt, was ich meine  
  
  
  
  
und du musst nicht  
aber du könntest  
noch 'n bisschen  
länger bleiben  
willst du nicht länger bleiben?  
das ist echt kein Problem  
willst du nicht länger bleiben?  
und warum willst du jetzt schon geh'n?  
willst du nicht länger bleiben?  
das ist echt kein Problem  
willst du nicht länger bleiben?  
und warum willst du jetzt schon geh'n?  
  
soll ich noch kurz zum Kiosk geh'n?  
und dann kauf' ich so 'ne billige Flasche Wein  
und die trinken wir zu zweit  
und dann rauchen wir am Fenster  
aber wir müssen 'n bisschen leiser sein  
sonst wacht mein Mitbewohner auf  
und dann will der auch 'was trinken  
  
und du probierst schon den ganzen Abend zu geh'n,  
ohne dass es komisch ist  
aber ich sorg' schon dafür, dass es immer komisch ist  
willst du nicht länger bleiben?  
das ist echt kein Problem  
willst du nicht länger bleiben  
und warum willst du jetzt schon geh'n?  
willst du nicht länger bleiben?  
das ist echt kein Problem  
willst du nicht länger bleiben?  
und warum willst du jetzt schon geh'n?  
  
und warum willst du jetzt schon geh'n?  
und warum willst du jetzt schon geh'n?
