## Bitte bleib

Und du sagst, dass du gehst.  
Und du sagst, dass du meinst was du sagst, wenn du gehst.  
Und du sagst, dass du hoffst das ich das versteh'.  
Und du sagst, dass du hoffst das du einer meiner Freunde bleibst.  
Und das du mir 'mal schreibst wie es dir geht.  
Und du sagst, es tut dir fürchterlich leid.  
  
Und dann sagst du zu mir: sag' doch auch mal was.  
Und dann denk' ich mir: gut, bevor du gehst sag' ich was.  
  
  
  
  
Bitte bleib', bitte bleib', bitte bleib', bitte bleib' nicht wie du bist.  
Bitte bleib', bitte bleib', bitte bleib', bitte bleib' nicht wie du bist.  
Bitte bleib', bitte bleib', bitte bleib', bitte bleib' nicht wie du bist.  
Und wunder' dich nicht, wenn alles scheisse ist und du mich vermisst.  
Und vielleicht hätt' ich das auch nur ganz gern gesagt, aber hab' es nicht.  
  
Eigentlich wollt' ich dir nur sagen: ich hab' dir nicht verzieh'n.  
Man könnte sozusagen sagen: ich bin krass bedient.  
Und ich versprech' dir, wenn wir uns das nächste Mal zufällig irgendwo seh'n  
Dann wird das richtig peinlich  
  
Und überhaupt dieses: sag doch auch mal was!  
Ich sag doch dauernd was.  
Ich kann mich langsam selber nicht mehr hör'n.  
Bitte bleib', bitte bleib', bitte bleib', bitte bleib' nicht wie du bist.  
Bitte bleib', bitte bleib', bitte bleib', bitte bleib' nicht wie du bist.  
Bitte bleib', bitte bleib', bitte bleib', bitte bleib' nicht wie du bist.  
Und ruf mich nicht mitten in der Nacht an, wenn alles Scheisse ist und du mich vermisst.
