## Du bist überall

Das hört sich jetzt erst mal komisch an,  
Aber ich geh' so verdammt gern alleine auf Konzerte  
Das hört sich jetzt erst mal komisch an,  
Aber mir ist scheiß egal, ob ich hier Empfang hab oder nicht  
Das hört sich jetzt erst mal komisch an,  
Aber es ist kein schönes Gefühl, bei 'nem Liebeslied die ganze Zeit mit einem Handy gefilmt zu werden  
Den Scheiß guckst du dir eh nie wieder an  
Und jetzt mal ganz im Ernst,  
Wenn du die ganze Zeit so dastehst,  
Der Typ hinter dir sieht überhaupt nichts und fuckt sich heimlich ab  
  
  
  
  
Ja! Und du bist überall  
Aber nicht hier bei mir  
Und du bist überall  
Aber nicht hier bei mir  
Und du bist überall  
Aber nicht hier bei mir  
Aber nicht hier bei mir!  
  
Und jetzt mal ganz im Ernst, wenn du dir das Konzert unbedingt nochmal anschauen willst,  
Wir nehmen das hier in hervorragender Bildqualität auf und du kannst dir das nachher ganz in Ruhe angucken  
Und außerdem, ich will eure Gesichter sehn' und nicht eure Handyhüllen  
Man kann das Handy auch ausmachen, macht man im Kino übrigens auch so  
  
Und ja! Du bist überall  
Aber nicht hier bei mir  
Und du bist überall  
Aber nicht hier bei mir  
Und du bist überall  
Aber nicht hier bei mir  
Aber nicht hier bei mir!  
  
Also einfach einmal viel zu teures Bier trinken, tanzen und an nichts anderes denken  
  
1, 2, 3, 4
