## Nicht nichts

Ich liege seit Tagen in meinem Bett und habe nichts zu tun  
Und nach dem Aufstehen fange ich an, mich auszuruhen.  
Ich überlege oft,  
Ob ich dir schreibe und ärger mich, weil ich immer liegen bleibe.  
  
Jetzt fehlt mir so viel, was mir wegen dir gefiel.  
Ich schreie zu Hause gegen die Wand und  
Draußen stumm in mich hinein und manchmal denke ich,  
Und manchmal denke ich, ich müsste wieder mit dir zusammen sein.  
  
Nicht Nichts ohne dich,  
Aber weniger, viel weniger für mich.  
Nicht Nichts ohne dich,  
Aber weniger, viel weniger für mich.  
  
  
  
  
Und dann höre ich mir die Kommentare meiner Freunde an,  
Weil ja jeder 'was dazu sagen kann.  
Aber eigentlich will ich das alles gar  
Nicht hören, weil mich diese Ratschläge stören.  
  
Und jetzt fehlt mir so viel, was mir wegen dir gefiel.  
Ich schreie zu Hause gegen die Wand und  
Draußen stumm in mich hinein und manchmal denke ich,  
Und manchmal denke ich, wir müssten wieder zusammen sein.  
  
Nicht Nichts ohne dich,  
Aber weniger, viel weniger für mich.  
Nicht Nichts ohne dich,  
Aber weniger, viel weniger für mich.  
  
Und dann liege ich wieder in meinem Bett und habe nichts zu tun  
Und du schreibst mir, dass du nichts mehr von mir hören willst.  
Und dann denke ich, ich habe dir nie alles gesagt, aber immerhin  
Nicht Nichts.
