## Barfuß am Klavier

Und ich sitz schon wieder  
Barfuß am Klavier  
Ich träume Liebeslieder  
und sing dabei von Dir  
Und du und ich  
wir waren wunderlich  
Nicht für mich  
für die die es störte  
wenn man uns Nachts hörte  
  
Ich hab mit dir gemeinsam einsam rumgesessen und geschwiegen  
ich erinner mich am Besten ans gemeinsam einsam liegen  
jeden Morgen  
danach bei dir  
du nackt im Bett und ich Barfuß am Klavier  
  
  
  
  
Und ich sitz schon wieder  
Barfuß am Klavier  
Ich träume Liebeslieder  
und sing dabei von Dir  
Und du und ich  
  
wir waren mal Wir  
und sind jetzt nicht  
du da, ich hier  
Du wolltest alles wissen  
und das hat mich vertrieben  
  
eigentlich dich, du bist nicht länger geblieben  
bei mir  
also sitz ich um zu lieben lieber Barfuß am Klavier  
  
Und ich sitz schon wieder  
Barfuß am Klavier  
Ich träume Liebeslieder  
und sing dabei von Dir  
und du und ich  
das war zu wenig  
  
Und ich sitz schon wieder  
Barfuß am Klavier  
und träum dabei von Dir  
ich träum dabei von dir  
ich träum dabei von dir
