## 21, 22, 23

Und du wirst 21, 22, 23,  
Und du kannst noch gar nicht wissen, was du willst.  
Und du wirst 24, 25, 26,  
Und du tanzt nicht mehr wie früher.  
  
Du und deine Freunde,  
Ihr seid alle am studieren  
Und ihr wartet drauf,  
Dass irgendwas passiert  
  
Hast du überhaupt 'ne Ahnung wo du gerade stehst?  
Du verschwendest deine Jugend  
Zwischen Kneipen und WG's  
  
Und du wirst 21, 22, 23,  
Und du kannst noch gar nicht wissen, was du willst.  
Und du wirst 24, 25, 26,  
Und du tanzt nicht mehr wie früher.  
  
  
  
  
Manchmal wirst du melancholisch im Straßenlaternenlicht.  
Am Wochenende gehst du feiern  
Und machst dich natürlich dicht.  
Und du hälst deine Träume absichtlich klein,  
Um am Ende nicht enttäuscht zu sein.  
  
Und du wirst 21, 22, 23,  
Und du kannst noch gar nicht wissen, was du willst.  
Und du wirst 24, 25, 26,  
Und du tanzt nicht mehr wie früher.  
  
Du sagst immer, das liegt alles nicht an dir  
Und bestellst dir noch ein Bier.  
Und wenn ich dich dann frage, was du werden willst,  
Sagst du immer nur "Ich weiß nicht. Hauptsache nicht Mitte dreißig.  
Hauptsache nicht Mitte 30"  
  
Und du wirst 21, 22, 23,  
Und du kannst noch gar nicht wissen, was du willst.  
Und du wirst 24, 25, 26,  
Und du tanzt nicht mehr wie früher.  
  
Und du wirst 21, 22, 23, 24, 25, 26, 27, 28, 29 ...
