## Jeden Morgen

Jeden Morgen war ich warm und wurde kalt  
Und die Geräuschgewalt hat mir ins Ohr gebissen  
Und ich frage mich wann werde ich alt?  
Und habe ich überhaupt 'n Gewissen?  
  
Ich will nicht jeden Morgen von neuem  
Letzte Nacht bereuen  
  
Jeden Morgen klagt mein Magen  
Und der Spiegel spricht mich schuldig  
Und mein Kopf stellt tausend Fragen  
Und wird langsam ungeduldig  
Er wird langsam ungeduldig  
  
  
  
  
Ich will nicht jeden Morgen von neuem  
Letzte Nacht bereuen  
Ich würd viel lieber jeden Morgen von neuem  
Von dir träumen  
  
Jeden morgen bin ich heiser bis wolkig  
Und der Winter verfolgt mich  
Und ich fülle in Sekunden meinen Bauch  
Mit Kaffee und Zigarettenrauch  
  
Und dann geh ich  
Weil mich irgendwas treibt  
Obwohl ich weiß  
Dass mein Kopf noch lange liegen bleibt  
  
Ich will nicht jeden Morgen von neuem  
Letzte Nacht bereuen  
Ich würd viel lieber jeden Morgen von neuem  
Von dir träumen  
Ich würd viel lieber von dir träumen  
Ich würd viel lieber von dir träumen
