## Oft gefragt

Du hast mich angezogen, ausgezogen, großgezogen  
Und wir sind umgezogen, ich hab dich angelogen:  
"Ich nehme keine Drogen  
Und in der Schule war ich auch"  
  
Du hast dich oft gefragt, was mich zerreißt  
Ich wollte nicht, dass du es weißt  
Du warst allein zu Haus', hast mich vermisst  
Und dich gefragt, was du noch für mich bist  
Und dich gefragt, was du noch für mich bist  
  
Zuhause bist immer nur du  
Zuhause bist immer nur du  
  
Du hast mich abgeholt und hingebracht  
Bist mitten in der Nacht wegen mir aufgewacht  
Ich hab in letzter Zeit so oft daran gedacht  
  
  
  
  
Wir waren in Prag, Paris und Wien  
In der Bretagne und Berlin, aber nicht in Kopenhagen  
Du hast dich oft gefragt, was mich zerreißt  
Und ich hab' aufgehört, mich das zu fragen  
  
Du warst allein zu Haus', hast mich vermisst  
Und dich gefragt, was du noch für mich bist  
Und dich gefragt, was du noch für mich bist  
  
Zuhause bist immer nur du  
Zuhause bist immer nur du  
  
Ich hab keine Heimat, ich hab nur dich  
Du bist zuhause für immer und mich  
Du bist zuhause für immer und mich  
Du bist zuhause für immer und mich  
Du bist zuhause für immer und mich  
Du bist zuhause für immer und mich  
Hab keine Heimat, ich hab nur dich  
Du bist zuhause für immer und mich
