## Mir wär lieber Du weinst

Wir treffen uns seit Tagen nur noch in deinem Bett  
Ich vermisse deine Fragen und du bist viel zu nett  
Ich bin zu jung und noch nicht alt genug, und das mit uns tut mir nicht gut  
Und ich würd' mich so gern von dir entfernen  
  
Und ich will nicht mehr wissen, wo du pennst  
Ich will nicht mehr wissen, wie du mich nennst  
Ich will nicht mehr wissen, dass du mich so gut kennst  
Ich versteh' doch eh nicht, was du meinst  
Und du versprichst nicht ein Versprechen  
Nur um mich zu unterbrechen  
Und du versprichst mir ein Versprechen  
Nur um mich zu unterbrechen  
  
  
  
  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Ich versteh' doch eh nicht, was du meinst  
  
Und ich will wirklich nicht mehr wissen, wo du pennst  
Ich will nicht mehr wissen, wie du mich nennst  
Ich will nicht mehr wissen, dass du mich so gut kennst  
Ich versteh' doch eh nicht, was du meinst  
  
Und du versprichst mir Versprechen  
Nur um mich zu unterbrechen  
Und du versprichst dich beim Versprechen  
Nur um mich zu unterbrechen  
  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Ich versteh' doch eh nicht, was du meinst  
  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Mir wär' lieber du weinst, mir wär' lieber du weinst  
Wir drehen uns im Kreis
